### ISSUE TITLE
Footer height is not fixed

### ISSUE THREAD

**Issue by jothikiruthika-jltasia** [JLTiPL/JUIS#1]
The footer occupies the whole page, when there is no content. Ideally, the height of the footer should be fixed, such that, even when there is no content, the footer should stay at the bottom of the page.
 Ref image attached at - 
https://cloud.githubusercontent.com/assets/12709092/15850016/3a05d82e-2cc8-11e6-82ba-25a124514c3e.png

**Comment by cliener** [comment]
Fixed! Works in IE10+

**Comment by jothikiruthika-jltasia** [comment]
Great !!  Thank You Chris .

Regards,
JothiKiruthika Viswanathan |  JLT Interactive Pte Ltd (Co Reg: 200504254W)
138 Market Street, #07-01 CapitaGreen, Singapore 048946
Direct Dial: +65 6411 9296 | Mobile: +65 8248 8853
jothi_kiruthika@jltasia.com<mailto:jothi_kiruthika@jltasia.com> | www.jltinteractive.com<http://www.jltinteractive.com/>
[JLTILog]
Transparency . Connectivity . Innovation
